### ISSUE TITLE
Whats `client`?

### ISSUE THREAD

**Issue by Luna-devv** [AntiScamBot/backend#3]
https://github.com/AntiScamBot/backend/blob/047a3bf80c39bc5dbe1f6b4faa0aaafe588c6a72/api/app.js#L58

There is an `client.on()` event listener but client isn't defined anywhere

**Comment by InvalidLenni** [comment]
oh, thanks for letting me know. The ``client.on()`` event listener should actually be for the Discord bot, have the remaining part therefore also removed.

**Comment by InvalidLenni** [comment]
Apparently I also forgot to remove the remaining part, was there tired
